module.exports = {
  DATABASE_CONNECTION: process.env.DATABASE_CONNECTION,
  JWT_SECRET: process.env.JWT_SECRET,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
  CLOUDINARY_API_CLOUD: process.env.CLOUDINARY_API_CLOUD,
};
